### ISSUE TITLE
Why not add i18n support?

### ISSUE THREAD

**Issue by soldierm** [greymd/ojichat#19]
i18n may be awesome.😈

**Comment by greymd** [comment]
Hi, @soldierm chan ❗💗😍

I understand that i18n is helpful 💪❗for other developers all over the world💗😍❗❗
Actually ✋ my other repositories are discovered in English 😄😂😄

However 😨😨😨 regarding this repository, I believe, Japanese 🇯🇵 should basically be used 🙇
Let me add some description to README.md in English 😎😎 if I have time 😝
And, you will understand that even if it supports i18n, nobody gets fun❗😇

Because to understand "why this command's result is fun" 💗,
it is necessary to understand modern Japanese and Japanese culture very deeply😻❗
In addition✋, to maintain this command, such the knowledge is also required because its algorithm is based on the behavior of Japanese middle-aged male 👴👴👴 reported by [related work](https://kogusoku.com/archives/2939)🤔
